FROM jeboehm/shopware:base
MAINTAINER Jeffrey Boehm <jeffrey.boehm@twt.de>

ENV SHOPWARE_VERSION=5.2.22

RUN wget -qO /root/shopware.tar.gz https://github.com/shopware/shopware/archive/v$SHOPWARE_VERSION.tar.gz
